to_do_list/urls.py
from django.contrib import admin
from django.urls import path,include
import todolist.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include(todolist.urls)),
]

todolist/urls.py
from django.urls import path,include
from . import views

app_name ="todolist"
#app_name是给app起名防止和其他app的网址名重合
urlpatterns = [
    path('home/',views.home,name="主页"),
    #name是给网址起名，方便更改
    path('about/',views.about,name="关于"),
    path('edit/<eachthing_id>',views.edit,name="编辑"),
    path('del/<eachthing_id>',views.delete,name="删除"),
    path('cross/<eachthing_id>',views.cross,name="划掉"),
]

todolist/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    
    thing = models.CharField(max_length=50)
    done = models.BooleanField(default=False)
    def __str__(self):
        #输出的时候会显示成XX
        return self.thing 

    def get_absolute_url(self):
        return reverse("Todo_detail", kwargs={"pk": self.pk})

todolist/views.py
from django.shortcuts import render,redirect
from .models import Todo

# Create your views here.
def home(request):
    if request.method == "POST":
        if request.POST['待办事项'] =="":
            conent={'清单':Todo.objects.all(),'警告':"请输入内容!"}
            return render(request,"todolist/home.html",conent)
        else:
            a_row = Todo(thing=request.POST['待办事项'],done=False)
            a_row.save() #一定要保存才能存入数据
            conent={'清单':Todo.objects.all(),'信息':"添加成功!"}
            return render(request,"todolist/home.html",conent)
    elif request.method == "GET":
        conent={'清单':Todo.objects.all()}
        return render(request,"todolist/home.html",conent)
    #运送网页
def about(request):
    return render(request,"todolist/about.html")
    #重新渲染界面，运送（网址）

def edit(request,eachthing_id):
    a=Todo.objects.get(id=eachthing_id)
    content = {"change":a.thing}
    if request.method == "POST":
        if request.POST['changetodo'] =="":
            return render(request,"todolist/edit.html",{'警告':"请输入内容!"})
        
        a.thing=request.POST["changetodo"]
        a.save()
        return redirect("todolist:主页")
    elif request.method == "GET":
        content = {"change":a.thing}
        return render(request,"todolist/edit.html",content)
def delete(request,eachthing_id):
    #跳转到主页(网页)
    a=Todo.objects.get(id=eachthing_id)
    a.delete()
    return redirect("todolist:主页")
def cross(request,eachthing_id):
    if request.POST["state"] == "done":
        a=Todo.objects.get(id=eachthing_id)
        a.done =True
        a.save()
        return redirect("todolist:主页")
    else:
        a=Todo.objects.get(id=eachthing_id)
        a.done =False
        a.save()
        return redirect("todolist:主页")

todolist/templates/todolist/about.html
{% extends 'todolist/base.html' %}
{% load static  %}
{% block css %}{% static 'todolist/css/about.css' %}{% endblock css %}
{% block 标题 %}关于本站{% endblock 标题 %}
<!doctype html>
{% block 高亮2 %}active{% endblock 高亮2 %}
{% block 主体 %}
  <br>
  <br>
   <a id="main">一款小巧、简洁的待办清单工具，帮你规划日常事务。</a>
   <br>
   <a>Power By Django</a>
   <br>
   <a>&copy;  黄占杰</a>
{% endblock 主体  %}

todolist/templates/todolist/base.html
{% load static  %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block 标题 %}
    {% endblock 标题 %}</title>
    <!--label icon-->
    <link href="{% static 'todolist/icons/icon_list.png' %}" rel="shortcut icon" >
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link rel="stylesheet" href ="{% static 'todolist/css/base.css' %}">
    <link rel="stylesheet" href ="{% block css %}{% endblock css %}">
    <!-- Custom styles for this template -->
    <link href="navbar-top.css" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% block 高亮1 %}{% endblock 高亮1 %}">
        <a class="nav-link" href="{% url 'todolist:主页' %}"><img src="{% static 'todolist/images/logo_list.png' %}" width="33" height ="33" class="d-inline-block align-top" alt="">    待办清单</a>
      </li>
      <li class="nav-item {% block 高亮2 %}{% endblock 高亮2 %}">
        <a class="nav-link" href="{% url 'todolist:关于' %}">关于本站</a>
      </li>
    </ul>
    <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end" method="POST" action="">
      {% csrf_token %}
      <input name="待办事项"class="form-control mr-sm-2" type="text" placeholder="添加待办事项" aria-label="待办清单">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
    </form>
  </div>
</nav>
<main role="main" class ="container">
{% block 主体 %}
{% endblock 主体 %}

</main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script></body>
</html>

todolist/templates/todolist/edit.html
<!doctype html>

{% extends 'todolist/base.html' %}
{% load static  %}
{% block css %}{% static 'todolist/css/edit.css' %}{% endblock css %}
{% block 标题 %}编辑{% endblock 标题 %}
<!doctype html>
{% block 主体 %}
  <br>
  <br> 
<form id="form-edit" method ="POST" action=''>
  <div class="form-group">
    <label for="editTodo"></label>
    {% csrf_token %}
    <input name="changetodo" class="form-control form-control-lg" id="editTodo" type="text" value="{{ change }}">
    <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
  </div>
    {% if 警告 %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><center>{{ 警告 }} </center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  <button type="submit" class="btn btn-primary btn-lg btn-block">提交</button>
</form>
{% endblock 主体 %}

todolist/templates/todolist/home.html
{% extends 'todolist/base.html' %}
<!doctype html>
{% load static  %}
{% block css %}{% static 'todolist/css/home.css' %}{% endblock css %}
{% block 高亮1 %}active{% endblock 高亮1 %}
{% block 标题 %}我的个人代办清单{% endblock 标题 %}
  {% block 主体 %}
  {% if 警告 %}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong><center>{{ 警告 }} </center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% if 信息 %}
  <div class="alert alert-primary alert-dismissible fade show" role="alert">
    <strong><center>{{ 信息 }} </center></strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
  </div>
  
  {% endif %}
    <br>
    <div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-light">
        <tr>
            <th>序号</th>
            <th>待办事项</th>
            <th>编辑</th>
            <th>做完喽</th>
            <th>删除</th>
        </tr>
        </thead>
        <tbody class="no-underline">
         {% for eachthing in 清单 %}
          {% if eachthing.done %}
          <tr class="table-dark">
            <th><a class="text-dark" scope="row">{{ forloop.counter }}</th>
            <td><a class="text-dark" id="line-through">{{ eachthing.thing }}</td>
            <td><a class="text-secondary"  href="#">不可编辑</a></td>
            <td>
                 <form method ="POST" action="{% url 'todolist:划掉' eachthing.id %}">
                    {% csrf_token %}
                    <input name="state" type="hidden" value="notdoneyet">
                    <button type="submit" class="btn btn-primary btn-sm">撤销</button>
                </form>
            </td>
            <td>
                <form method ="POST" action="{% url 'todolist:删除' eachthing.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm">删除</button>
                </form>
            </td>
          </tr>
          {% else %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ eachthing.thing}}</td>
            <td>
                <a class="text-info" href="{% url 'todolist:编辑' eachthing.id %}">
                    <button type="submit" class ="btn btn-primary btn-sm">编辑</button>
                </a>
            </td>
            <td>
                <form method ="POST" action="{% url 'todolist:划掉' eachthing.id %}">
                    {% csrf_token %}
                    <input name="state" type="hidden" value="done">
                    <button type="submit" class="btn btn-primary btn-sm">划掉</button>
                </form>
            </td>
            {% comment %} <td><a class="text-warning" href="{% url 'todolist:删除' eachthing.id %}">删除</a></td> {% endcomment %}
            <td>
                <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModal{{ forloop.counter }}">删除</button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModal{{ forloop.counter }}Label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModal{{ forloop.counter }}Label">请确认删除</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                <div class="modal-body">
                    你确定要删除<strong>未办事项：   <font color="#FF0000">{{ eachthing.thing }}</font> </strong>吗？(请不要放弃哟~)
                </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                        <form method ="POST" action="{% url 'todolist:删除' eachthing.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary ">删除</button>
                        </form>

                        </div>
                    </div>
                </div>
            </div>
            </td>
         </tr>
          {% endif %}
         
        {% endfor %}
         
        {% comment %}<tr>
            <th scope="row">2</th>
            <td>看一会小说</td>
            <td><a class="text-info"  href="#">编辑</a></td>
            <td><a class="text-info"  href="#">划掉</a></td>
            <td><a class="text-warning" href="#">删除</a></td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>散散步</td>
            <td><a class="text-info"  href="#">编辑</a></td>
            <td><a class="text-info"  href="#">划掉</a></td>
            <td><a class="text-warning" href="#">删除</a></td>
        </tr>
        <tr class="table-dark">
            <th><a class="text-dark" scope="row">4</th>
            <td><a class="text-dark" id="line-through">去超市</td>
            <td><a class="text-secondary"  href="#">不可编辑</a></td>
            <td><a class="text-info">撤销</td>
            <td><a class="text-danger" href="#">删除</a></td>
        </tr> {% endcomment %}
        </tbody>
    </table>
    </div>
  {% endblock 主体 %}